#' @title BUSCAR_ORIENTACOES_EM_ANDAMENTO_MESTRADO
#'
#' 
#'
#' @param doc a list of Lattes CV XML files
#'
#' 
#'
#'
#'
#' @export BUSCAR_ORIENTACOES_EM_ANDAMENTO_MESTRADO

BUSCAR_ORIENTACOES_EM_ANDAMENTO_MESTRADO<-function(doc){


ORIENTACOES_EM_ANDAMENTO_MESTRADO<-list()


OrientacoesMestrado=xmlRoot(doc)[["DADOS-COMPLEMENTARES"]][["ORIENTACOES-EM-ANDAMENTO"]][c("ORIENTACAO-EM-ANDAMENTO-DE-MESTRADO") ]

if(length(OrientacoesMestrado) != 0) { 
	for(orientacao in OrientacoesMestrado){
	 
		DADOS_BASICOS_DA_ORIENTACAO_EM_ANDAMENTO_DE_MESTRADO<-new.env(parent=emptyenv())
		  atributos<-xmlAttrs(orientacao[["DADOS-BASICOS-DA-ORIENTACAO-EM-ANDAMENTO-DE-MESTRADO"]])
		  DADOS_BASICOS_DA_ORIENTACAO_EM_ANDAMENTO_DE_MESTRADO$NATUREZA<- ValidateXmlAttr(atributos,"NATUREZA")


		  DADOS_BASICOS_DA_ORIENTACAO_EM_ANDAMENTO_DE_MESTRADO$TITULO_DO_TRABALHO<-ValidateXmlAttr(atributos,"TITULO-DO-TRABALHO")
                  DADOS_BASICOS_DA_ORIENTACAO_EM_ANDAMENTO_DE_MESTRADO$ANO<-ValidateXmlAttr(atributos,"ANO")
     
		  DADOS_BASICOS_DA_ORIENTACAO_EM_ANDAMENTO_DE_MESTRADO$PAIS<- ValidateXmlAttr(atributos,"PAIS")
	

		

		DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_MESTRADO<-new.env(parent=emptyenv())
		
		
		tryCatch(atributos<-xmlAttrs(orientacao[["DETALHAMENTO-DA-ORIENTACAO-EM-ANDAMENTO-DE-MESTRADO"]])
	,

	error = function(e) {
		atributos<-NULL
	
	}  )

		  DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_MESTRADO$TIPO_DE_ORIENTACAO<- ValidateXmlAttr(atributos,"TIPO-DE-ORIENTACAO")

                  DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_MESTRADO$NOME_DO_ORIENTADO<- ValidateXmlAttr(atributos,"NOME-DO-ORIENTANDO")

	          DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_MESTRADO$CODIGO_INSTITUICAO<-ValidateXmlAttr(atributos,"CODIGO-INSTITUICAO")

                  DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_MESTRADO$NOME_INSTITUICAO<- ValidateXmlAttr(atributos,"NOME-INSTITUICAO")

                  DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_MESTRADO$CODIGO_CURSO<- ValidateXmlAttr(atributos,"CODIGO-CURSO")
                  DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_MESTRADO$NOME_CURSO<- ValidateXmlAttr(atributos,"NOME-CURSO")
		  DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_MESTRADO$FLAG_BOLSA<- ValidateXmlAttr(atributos,"FLAG-BOLSA")
		  DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_MESTRADO$CODIGO_AGENCIA_FINANCIADORA<- ValidateXmlAttr(atributos,"CODIGO-AGENCIA-FINANCIADORA")
		  DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_MESTRADO$NOME_DA_AGENCIA<- ValidateXmlAttr(atributos,"NOME-DA-AGENCIA")
		  DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_MESTRADO$NUMERO_ID_ORIENTADO<- ValidateXmlAttr(atributos,"NUMERO-ID-ORIENTADO")


	      		    
	
              
	     ORIENTACAO_EM_ANDAMENTO_DE_MESTRADO<-new.env(parent=emptyenv())

	     
	       ORIENTACAO_EM_ANDAMENTO_DE_MESTRADO$DETALHAMENTO<-DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_MESTRADO
	       ORIENTACAO_EM_ANDAMENTO_DE_MESTRADO$DADOS_BASICOS<-DADOS_BASICOS_DA_ORIENTACAO_EM_ANDAMENTO_DE_MESTRADO
	      
	       ORIENTACAO_EM_ANDAMENTO_DE_MESTRADO$IDLATTES<-"NULL"
	       ORIENTACAO_EM_ANDAMENTO_DE_MESTRADO$NOME_COMPLETO<-"NULL"

	    ORIENTACOES_EM_ANDAMENTO_MESTRADO<-c(ORIENTACOES_EM_ANDAMENTO_MESTRADO,list(ORIENTACAO_EM_ANDAMENTO_DE_MESTRADO))
	  
	  }
	  Resultado<-ORIENTACOES_EM_ANDAMENTO_MESTRADO
 } else{ Resultado<-NULL}

Resultado

}




