BUSCAR_OUTRAS_ORIENTACOES_CONCLUIDAS<-function(doc){


OUTRAS_ORIENTACOES_CONCLUIDAS<-list()


Orientacoes=xmlRoot(doc)[["OUTRA-PRODUCAO"]][["ORIENTACOES-CONCLUIDAS"]][c("OUTRAS-ORIENTACOES-CONCLUIDAS") ]

if(length(Orientacoes) != 0) { 
	for(orientacao in Orientacoes){
	 
		DADOS_BASICOS_DE_OUTRAS_ORIENTACOES_CONCLUIDAS<-new.env(parent=emptyenv())
		  atributos<-xmlAttrs(orientacao[["DADOS-BASICOS-DE-OUTRAS-ORIENTACOES-CONCLUIDAS"]])
		DADOS_BASICOS_DE_OUTRAS_ORIENTACOES_CONCLUIDAS$NATUREZA<- ValidateXmlAttr(atributos,"NATUREZA")
		DADOS_BASICOS_DE_OUTRAS_ORIENTACOES_CONCLUIDAS$TIPO<- ValidateXmlAttr(atributos,"TIPO")


		DADOS_BASICOS_DE_OUTRAS_ORIENTACOES_CONCLUIDAS$TITULO_DO_TRABALHO<-ValidateXmlAttr(atributos,"TITULO")
                DADOS_BASICOS_DE_OUTRAS_ORIENTACOES_CONCLUIDAS$ANO<-ValidateXmlAttr(atributos,"ANO")
     
		DADOS_BASICOS_DE_OUTRAS_ORIENTACOES_CONCLUIDAS$PAIS<- ValidateXmlAttr(atributos,"PAIS")
	

		

		DETALHAMENTO_DE_OUTRAS_ORIENTACOES_CONCLUIDAS<-new.env(parent=emptyenv())
		atributos<-xmlAttrs(orientacao[["DETALHAMENTO-DE-OUTRAS-ORIENTACOES-CONCLUIDAS"]])

		  DETALHAMENTO_DE_OUTRAS_ORIENTACOES_CONCLUIDAS$TIPO_DE_ORIENTACAO<- ValidateXmlAttr(atributos,"TIPO-DE-ORIENTACAO")

                  DETALHAMENTO_DE_OUTRAS_ORIENTACOES_CONCLUIDAS$NOME_DO_ORIENTADO<- ValidateXmlAttr(atributos,"NOME-DO-ORIENTADO")

	          DETALHAMENTO_DE_OUTRAS_ORIENTACOES_CONCLUIDAS$CODIGO_INSTITUICAO<-ValidateXmlAttr(atributos,"CODIGO-INSTITUICAO")

                  DETALHAMENTO_DE_OUTRAS_ORIENTACOES_CONCLUIDAS$NOME_INSTITUICAO<- ValidateXmlAttr(atributos,"NOME-DA-INSTITUICAO")

                  DETALHAMENTO_DE_OUTRAS_ORIENTACOES_CONCLUIDAS$CODIGO_CURSO<- ValidateXmlAttr(atributos,"CODIGO-CURSO")
                  DETALHAMENTO_DE_OUTRAS_ORIENTACOES_CONCLUIDAS$NOME_CURSO<- ValidateXmlAttr(atributos,"NOME-DO-CURSO")
		  DETALHAMENTO_DE_OUTRAS_ORIENTACOES_CONCLUIDAS$FLAG_BOLSA<- ValidateXmlAttr(atributos,"FLAG-BOLSA")
		  DETALHAMENTO_DE_OUTRAS_ORIENTACOES_CONCLUIDAS$CODIGO_AGENCIA_FINANCIADORA<- ValidateXmlAttr(atributos,"CODIGO-AGENCIA-FINANCIADORA")
		  DETALHAMENTO_DE_OUTRAS_ORIENTACOES_CONCLUIDAS$NOME_DA_AGENCIA<- ValidateXmlAttr(atributos,"NOME-DA-AGENCIA")
		  DETALHAMENTO_DE_OUTRAS_ORIENTACOES_CONCLUIDAS$NUMERO_ID_ORIENTADO<- ValidateXmlAttr(atributos,"NUMERO-ID-ORIENTADO")


	      		    
	
              
	     OUTRA_ORIENTACAO_CONCLUIDA<-new.env(parent=emptyenv())

	     
	       OUTRA_ORIENTACAO_CONCLUIDA$DETALHAMENTO<-DETALHAMENTO_DE_OUTRAS_ORIENTACOES_CONCLUIDAS
	       OUTRA_ORIENTACAO_CONCLUIDA$DADOS_BASICOS<-DADOS_BASICOS_DE_OUTRAS_ORIENTACOES_CONCLUIDAS
	      
	       OUTRA_ORIENTACAO_CONCLUIDA$IDLATTES<-"NULL"
	       OUTRA_ORIENTACAO_CONCLUIDA$NOME_COMPLETO<-"NULL"

	    OUTRAS_ORIENTACOES_CONCLUIDAS<-c(OUTRAS_ORIENTACOES_CONCLUIDAS,list(OUTRA_ORIENTACAO_CONCLUIDA))
	  
	  }
	  Resultado<-OUTRAS_ORIENTACOES_CONCLUIDAS
 } else{ Resultado<-NULL}

Resultado

}




