
#' @title BUSCAR_ORIENTACAO_EM_ANDAMENTO_DE_POS_DOUTORADO
#'
#' 
#'
#' @param doc a list of Lattes CV XML files
#'
#' 
#'
#'
#'
#' @export BUSCAR_ORIENTACAO_EM_ANDAMENTO_DE_POS_DOUTORADO

BUSCAR_ORIENTACAO_EM_ANDAMENTO_DE_POS_DOUTORADO<-function(doc){


ORIENTACOES_EM_ANDAMENTO_DE_POS_DOUTORADO<-list()


Orientacoes=xmlRoot(doc)[["DADOS-COMPLEMENTARES"]][["ORIENTACOES-EM-ANDAMENTO"]][c("ORIENTACAO-EM-ANDAMENTO-DE-POS-DOUTORADO") ]

if(length(Orientacoes) != 0) { 
	for(orientacao in Orientacoes){
	 
		DADOS_BASICOS_DA_ORIENTACAO_EM_ANDAMENTO_DE_POS_DOUTORADO<-new.env(parent=emptyenv())
		  atributos<-xmlAttrs(orientacao[["DADOS-BASICOS-DA-ORIENTACAO-EM-ANDAMENTO-DE-POS-DOUTORADO"]])
		DADOS_BASICOS_DA_ORIENTACAO_EM_ANDAMENTO_DE_POS_DOUTORADO$NATUREZA<- ValidateXmlAttr(atributos,"NATUREZA")


		DADOS_BASICOS_DA_ORIENTACAO_EM_ANDAMENTO_DE_POS_DOUTORADO$TITULO_DO_TRABALHO<-ValidateXmlAttr(atributos,"TITULO-DO-TRABALHO")
                DADOS_BASICOS_DA_ORIENTACAO_EM_ANDAMENTO_DE_POS_DOUTORADO$ANO<-ValidateXmlAttr(atributos,"ANO")
     
		DADOS_BASICOS_DA_ORIENTACAO_EM_ANDAMENTO_DE_POS_DOUTORADO$PAIS<- ValidateXmlAttr(atributos,"PAIS")
	

		

		DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_POS_DOUTORADO<-new.env(parent=emptyenv())
		atributos<-xmlAttrs(orientacao[["DETALHAMENTO-DA-ORIENTACAO-EM-ANDAMENTO-DE-POS-DOUTORADO"]])

		  DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_POS_DOUTORADO$TIPO_DE_ORIENTACAO<- ValidateXmlAttr(atributos,"TIPO-DE-ORIENTACAO")

                  DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_POS_DOUTORADO$NOME_DO_ORIENTADO<- ValidateXmlAttr(atributos,"NOME-DO-ORIENTANDO")

	          DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_POS_DOUTORADO$CODIGO_INSTITUICAO<-ValidateXmlAttr(atributos,"CODIGO-INSTITUICAO")

                  DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_POS_DOUTORADO$NOME_INSTITUICAO<- ValidateXmlAttr(atributos,"NOME-INSTITUICAO")

                  DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_POS_DOUTORADO$CODIGO_CURSO<- ValidateXmlAttr(atributos,"CODIGO-CURSO")
                  DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_POS_DOUTORADO$NOME_CURSO<- ValidateXmlAttr(atributos,"NOME-CURSO")
		  DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_POS_DOUTORADO$FLAG_BOLSA<- ValidateXmlAttr(atributos,"FLAG-BOLSA")
		  DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_POS_DOUTORADO$CODIGO_AGENCIA_FINANCIADORA<- ValidateXmlAttr(atributos,"CODIGO-AGENCIA-FINANCIADORA")
		  DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_POS_DOUTORADO$NOME_DA_AGENCIA<- ValidateXmlAttr(atributos,"NOME-DA-AGENCIA")
		  DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_POS_DOUTORADO$NUMERO_ID_ORIENTADO<- ValidateXmlAttr(atributos,"NUMERO-ID-ORIENTANDO")


	      		    
	
              
	     ORIENTACAO_EM_ANDAMENTO_DE_POS_DOUTORADO<-new.env(parent=emptyenv())

	     
	       ORIENTACAO_EM_ANDAMENTO_DE_POS_DOUTORADO$DETALHAMENTO<-DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_POS_DOUTORADO
	       ORIENTACAO_EM_ANDAMENTO_DE_POS_DOUTORADO$DADOS_BASICOS<-DADOS_BASICOS_DA_ORIENTACAO_EM_ANDAMENTO_DE_POS_DOUTORADO
	      
	       ORIENTACAO_EM_ANDAMENTO_DE_POS_DOUTORADO$IDLATTES<-"NULL"
	       ORIENTACAO_EM_ANDAMENTO_DE_POS_DOUTORADO$NOME_COMPLETO<-"NULL"

	    ORIENTACOES_EM_ANDAMENTO_DE_POS_DOUTORADO<-c(ORIENTACOES_EM_ANDAMENTO_DE_POS_DOUTORADO,list(ORIENTACAO_EM_ANDAMENTO_DE_POS_DOUTORADO))
	  
	  }
	  Resultado<-ORIENTACOES_EM_ANDAMENTO_DE_POS_DOUTORADO
 } else{ Resultado<-NULL}

Resultado

}




