#' @title BUSCAR_ORIENTACOES_CONCLUIDAS_DE_MESTRADO
#'
#' 
#'
#' @param files a list of Lattes CV XML files
#'
#' 
#'
#'
#'
#' @export BUSCAR_ORIENTACOES_CONCLUIDAS_DE_MESTRADO

BUSCAR_ORIENTACOES_CONCLUIDAS_DE_MESTRADO<-function(doc){


ORIENTACOES_CONCLUIDAS_DE_MESTRADO<-list()


OrientacoesMestrado=xmlRoot(doc)[["OUTRA-PRODUCAO"]][["ORIENTACOES-CONCLUIDAS"]][c("ORIENTACOES-CONCLUIDAS-PARA-MESTRADO") ]

if(length(OrientacoesMestrado) != 0) { 
	for(orientacao in OrientacoesMestrado){
	 
		DADOS_BASICOS_DE_ORIENTACOES_CONCLUIDAS_PARA_MESTRADO<-new.env(parent=emptyenv())
		  atributos<-xmlAttrs(orientacao[["DADOS-BASICOS-DE-ORIENTACOES-CONCLUIDAS-PARA-MESTRADO"]])
		DADOS_BASICOS_DE_ORIENTACOES_CONCLUIDAS_PARA_MESTRADO$NATUREZA<- ValidateXmlAttr(atributos,"NATUREZA")
		DADOS_BASICOS_DE_ORIENTACOES_CONCLUIDAS_PARA_MESTRADO$TIPO<- ValidateXmlAttr(atributos,"TIPO")


		DADOS_BASICOS_DE_ORIENTACOES_CONCLUIDAS_PARA_MESTRADO$TITULO_DO_TRABALHO<-ValidateXmlAttr(atributos,"TITULO")
                DADOS_BASICOS_DE_ORIENTACOES_CONCLUIDAS_PARA_MESTRADO$ANO<-ValidateXmlAttr(atributos,"ANO")
     
		DADOS_BASICOS_DE_ORIENTACOES_CONCLUIDAS_PARA_MESTRADO$PAIS<- ValidateXmlAttr(atributos,"PAIS")
	

		

		DETALHAMENTO_DE_ORIENTACOES_CONCLUIDAS_PARA_MESTRADO<-new.env(parent=emptyenv())
		atributos<-xmlAttrs(orientacao[["DETALHAMENTO-DE-ORIENTACOES-CONCLUIDAS-PARA-MESTRADO"]])

		  DETALHAMENTO_DE_ORIENTACOES_CONCLUIDAS_PARA_MESTRADO$TIPO_DE_ORIENTACAO<- ValidateXmlAttr(atributos,"TIPO-DE-ORIENTACAO")

                  DETALHAMENTO_DE_ORIENTACOES_CONCLUIDAS_PARA_MESTRADO$NOME_DO_ORIENTADO<- ValidateXmlAttr(atributos,"NOME-DO-ORIENTADO")

	          DETALHAMENTO_DE_ORIENTACOES_CONCLUIDAS_PARA_MESTRADO$CODIGO_INSTITUICAO<-ValidateXmlAttr(atributos,"CODIGO-INSTITUICAO")

                  DETALHAMENTO_DE_ORIENTACOES_CONCLUIDAS_PARA_MESTRADO$NOME_INSTITUICAO<- ValidateXmlAttr(atributos,"NOME-DA-INSTITUICAO")

                  DETALHAMENTO_DE_ORIENTACOES_CONCLUIDAS_PARA_MESTRADO$CODIGO_CURSO<- ValidateXmlAttr(atributos,"CODIGO-CURSO")
                  DETALHAMENTO_DE_ORIENTACOES_CONCLUIDAS_PARA_MESTRADO$NOME_CURSO<- ValidateXmlAttr(atributos,"NOME-DO-CURSO")
		  DETALHAMENTO_DE_ORIENTACOES_CONCLUIDAS_PARA_MESTRADO$FLAG_BOLSA<- ValidateXmlAttr(atributos,"FLAG-BOLSA")
		  DETALHAMENTO_DE_ORIENTACOES_CONCLUIDAS_PARA_MESTRADO$CODIGO_AGENCIA_FINANCIADORA<- ValidateXmlAttr(atributos,"CODIGO-AGENCIA-FINANCIADORA")
		  DETALHAMENTO_DE_ORIENTACOES_CONCLUIDAS_PARA_MESTRADO$NOME_DA_AGENCIA<- ValidateXmlAttr(atributos,"NOME-DA-AGENCIA")
		  DETALHAMENTO_DE_ORIENTACOES_CONCLUIDAS_PARA_MESTRADO$NUMERO_ID_ORIENTADO<- ValidateXmlAttr(atributos,"NUMERO-ID-ORIENTADO")


	      		    
	
              
	     ORIENTACAO_CONCLUIDA_DE_MESTRADO<-new.env(parent=emptyenv())

	     
	       ORIENTACAO_CONCLUIDA_DE_MESTRADO$DETALHAMENTO<-DETALHAMENTO_DE_ORIENTACOES_CONCLUIDAS_PARA_MESTRADO
	       ORIENTACAO_CONCLUIDA_DE_MESTRADO$DADOS_BASICOS<-DADOS_BASICOS_DE_ORIENTACOES_CONCLUIDAS_PARA_MESTRADO
	      
	       ORIENTACAO_CONCLUIDA_DE_MESTRADO$IDLATTES<-"NULL"
	       ORIENTACAO_CONCLUIDA_DE_MESTRADO$NOME_COMPLETO<-"NULL"

	    ORIENTACOES_CONCLUIDAS_DE_MESTRADO<-c(ORIENTACOES_CONCLUIDAS_DE_MESTRADO,list(ORIENTACAO_CONCLUIDA_DE_MESTRADO))
	  
	  }
	  Resultado<-ORIENTACOES_CONCLUIDAS_DE_MESTRADO
 } else{ Resultado<-NULL}

Resultado

}




