#' @title BUSCAR_ORIENTACOES_EM_ANDAMENTO_GRADUACAO
#'
#' 
#'
#' @param doc a list of Lattes CV XML files
#'
#' 
#'
#'
#'
#' @export BUSCAR_ORIENTACOES_EM_ANDAMENTO_GRADUACAO

BUSCAR_ORIENTACOES_EM_ANDAMENTO_GRADUACAO<-function(doc){


ORIENTACOES_EM_ANDAMENTO_GRADUACAO<-list()


OrientacoesGraduacao=xmlRoot(doc)[["DADOS-COMPLEMENTARES"]][["ORIENTACOES-EM-ANDAMENTO"]][c("ORIENTACAO-EM-ANDAMENTO-DE-GRADUACAO") ]

if(length(OrientacoesGraduacao) != 0) { 
	for(orientacao in OrientacoesGraduacao){
	 
		DADOS_BASICOS_DA_ORIENTACAO_EM_ANDAMENTO_DE_GRADUACAO<-new.env(parent=emptyenv())
		  atributos<-xmlAttrs(orientacao[["DADOS-BASICOS-DA-ORIENTACAO-EM-ANDAMENTO-DE-GRADUACAO"]])
		DADOS_BASICOS_DA_ORIENTACAO_EM_ANDAMENTO_DE_GRADUACAO$NATUREZA<- ValidateXmlAttr(atributos,"NATUREZA")


		  DADOS_BASICOS_DA_ORIENTACAO_EM_ANDAMENTO_DE_GRADUACAO$TITULO_DO_TRABALHO<-ValidateXmlAttr(atributos,"TITULO-DO-TRABALHO")
                  DADOS_BASICOS_DA_ORIENTACAO_EM_ANDAMENTO_DE_GRADUACAO$ANO<-ValidateXmlAttr(atributos,"ANO")
     
		  DADOS_BASICOS_DA_ORIENTACAO_EM_ANDAMENTO_DE_GRADUACAO$PAIS<- ValidateXmlAttr(atributos,"PAIS")
	

		

		DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_GRADUACAO<-new.env(parent=emptyenv())
		

	


		tryCatch(atributos<-xmlAttrs(orientacao[["DETALHAMENTO-DA-ORIENTACAO-EM-ANDAMENTO-DE-GRADUACAO"]])
	,

	error = function(e) {
	atributos<-NULL
	}  )

		  DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_GRADUACAO$TIPO_DE_ORIENTACAO<- ValidateXmlAttr(atributos,"TIPO-DE-ORIENTACAO")

                  DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_GRADUACAO$NOME_DO_ORIENTADO<- ValidateXmlAttr(atributos,"NOME-DO-ORIENTANDO")



	          DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_GRADUACAO$CODIGO_INSTITUICAO<-ValidateXmlAttr(atributos,"CODIGO-INSTITUICAO")

                  DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_GRADUACAO$NOME_INSTITUICAO<- ValidateXmlAttr(atributos,"NOME-INSTITUICAO")

                  DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_GRADUACAO$CODIGO_CURSO<- ValidateXmlAttr(atributos,"CODIGO-CURSO")
                  DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_GRADUACAO$NOME_CURSO<- ValidateXmlAttr(atributos,"NOME-CURSO")
		  DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_GRADUACAO$FLAG_BOLSA<- ValidateXmlAttr(atributos,"FLAG-BOLSA")
		  DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_GRADUACAO$CODIGO_AGENCIA_FINANCIADORA<- ValidateXmlAttr(atributos,"CODIGO-AGENCIA-FINANCIADORA")
		  DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_GRADUACAO$NOME_DA_AGENCIA<- ValidateXmlAttr(atributos,"NOME-DA-AGENCIA")
		  DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_GRADUACAO$NUMERO_ID_ORIENTADO<- ValidateXmlAttr(atributos,"NUMERO-ID-ORIENTANDO")


	      		    
	
              
	     ORIENTACAO_EM_ANDAMENTO_DE_GRADUACAO<-new.env(parent=emptyenv())

	     
	       ORIENTACAO_EM_ANDAMENTO_DE_GRADUACAO$DETALHAMENTO<-DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_GRADUACAO
	       ORIENTACAO_EM_ANDAMENTO_DE_GRADUACAO$DADOS_BASICOS<-DADOS_BASICOS_DA_ORIENTACAO_EM_ANDAMENTO_DE_GRADUACAO
	      
	       ORIENTACAO_EM_ANDAMENTO_DE_GRADUACAO$IDLATTES<-"NULL"
	       ORIENTACAO_EM_ANDAMENTO_DE_GRADUACAO$NOME_COMPLETO<-"NULL"

	    ORIENTACOES_EM_ANDAMENTO_GRADUACAO<-c(ORIENTACOES_EM_ANDAMENTO_GRADUACAO,list(ORIENTACAO_EM_ANDAMENTO_DE_GRADUACAO))
	  
	  }
	  Resultado<-ORIENTACOES_EM_ANDAMENTO_GRADUACAO
 } else{ Resultado<-NULL}

Resultado

}




