BUSCAR_ORIENTACOES_EM_ANDAMENTO_DE_INICIACAO_CIENTIFICA<-function(doc){


ORIENTACOES_EM_ANDAMENTO_DE_INICIACAO_CIENTIFICA<-list()


OrientacoesIniciacao=xmlRoot(doc)[["DADOS-COMPLEMENTARES"]][["ORIENTACOES-EM-ANDAMENTO"]][c("ORIENTACAO-EM-ANDAMENTO-DE-INICIACAO-CIENTIFICA") ]

if(length(OrientacoesIniciacao) != 0) { 
	for(orientacao in OrientacoesIniciacao){
	 
		DADOS_BASICOS_DA_ORIENTACAO_EM_ANDAMENTO_DE_INICIACAO_CIENTIFICA<-new.env(parent=emptyenv())
		  atributos<-xmlAttrs(orientacao[["DADOS-BASICOS-DA-ORIENTACAO-EM-ANDAMENTO-DE-INICIACAO-CIENTIFICA"]])
		DADOS_BASICOS_DA_ORIENTACAO_EM_ANDAMENTO_DE_INICIACAO_CIENTIFICA$NATUREZA<- ValidateXmlAttr(atributos,"NATUREZA")


		  DADOS_BASICOS_DA_ORIENTACAO_EM_ANDAMENTO_DE_INICIACAO_CIENTIFICA$TITULO_DO_TRABALHO<-ValidateXmlAttr(atributos,"TITULO-DO-TRABALHO")
                  DADOS_BASICOS_DA_ORIENTACAO_EM_ANDAMENTO_DE_INICIACAO_CIENTIFICA$ANO<-ValidateXmlAttr(atributos,"ANO")
     
		  DADOS_BASICOS_DA_ORIENTACAO_EM_ANDAMENTO_DE_INICIACAO_CIENTIFICA$PAIS<- ValidateXmlAttr(atributos,"PAIS")
	



		DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_INICIACAO_CIENTIFICA <- new.env(parent=emptyenv())
		


		tryCatch(atributos<-xmlAttrs(orientacao[["DETALHAMENTO-DA-ORIENTACAO-EM-ANDAMENTO-DE-INICIACAO-CIENTIFICA"]]) ,

	error = function(e) {
	atributos<-NULL 
	}  )

		


                  DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_INICIACAO_CIENTIFICA$NOME_DO_ORIENTADO<- ValidateXmlAttr(atributos,"NOME-DO-ORIENTANDO")

	          DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_INICIACAO_CIENTIFICA$CODIGO_INSTITUICAO<-ValidateXmlAttr(atributos,"CODIGO-INSTITUICAO")

                  DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_INICIACAO_CIENTIFICA$NOME_INSTITUICAO<- ValidateXmlAttr(atributos,"NOME-INSTITUICAO")

                  DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_INICIACAO_CIENTIFICA$CODIGO_CURSO<- ValidateXmlAttr(atributos,"CODIGO-CURSO")
                  DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_INICIACAO_CIENTIFICA$NOME_CURSO<- ValidateXmlAttr(atributos,"NOME-CURSO")
		  DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_INICIACAO_CIENTIFICA$FLAG_BOLSA<- ValidateXmlAttr(atributos,"FLAG-BOLSA")
		  DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_INICIACAO_CIENTIFICA$CODIGO_AGENCIA_FINANCIADORA<- ValidateXmlAttr(atributos,"CODIGO-AGENCIA-FINANCIADORA")
		  DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_INICIACAO_CIENTIFICA$NOME_DA_AGENCIA<- ValidateXmlAttr(atributos,"NOME-DA-AGENCIA")
		  DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_INICIACAO_CIENTIFICA$NUMERO_ID_ORIENTADO<- ValidateXmlAttr(atributos,"NUMERO-ID-ORIENTANDO")


	      		    
	
              
	     ORIENTACAO_EM_ANDAMENTO_DE_INICIACAO_CIENTIFICA<-new.env(parent=emptyenv())

	     
	       ORIENTACAO_EM_ANDAMENTO_DE_INICIACAO_CIENTIFICA$DETALHAMENTO<-DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_INICIACAO_CIENTIFICA
	       ORIENTACAO_EM_ANDAMENTO_DE_INICIACAO_CIENTIFICA$DADOS_BASICOS<-DADOS_BASICOS_DA_ORIENTACAO_EM_ANDAMENTO_DE_INICIACAO_CIENTIFICA
	      
	       ORIENTACAO_EM_ANDAMENTO_DE_INICIACAO_CIENTIFICA$IDLATTES<-"NULL"
	       ORIENTACAO_EM_ANDAMENTO_DE_INICIACAO_CIENTIFICA$NOME_COMPLETO<-"NULL"

	    ORIENTACOES_EM_ANDAMENTO_DE_INICIACAO_CIENTIFICA<-c(ORIENTACOES_EM_ANDAMENTO_DE_INICIACAO_CIENTIFICA,list(ORIENTACAO_EM_ANDAMENTO_DE_INICIACAO_CIENTIFICA))
	  
	  }
	  Resultado<-ORIENTACOES_EM_ANDAMENTO_DE_INICIACAO_CIENTIFICA
 } else{ Resultado<-NULL}


Resultado

}




