.onLoad <- function (libname, pkgname)
{
    # make data set names global to avoid CHECK notes
    utils::globalVariables ("read.table")
    utils::globalVariables ("xmlRoot")
    utils::globalVariables ("xmlGetAttr")
    utils::globalVariables ("xmlAttrs")
    utils::globalVariables ("write.graph")
    utils::globalVariables ("hash")
    utils::globalVariables ("xmlParse")
    utils::globalVariables ("elemento_raiz")
    utils::globalVariables (".set")
    utils::globalVariables ("keys")
    utils::globalVariables ("fromJSON")
    utils::globalVariables ("combn")
    utils::globalVariables ("%>%")
    utils::globalVariables ("unite")
    utils::globalVariables ("V1")
    utils::globalVariables ("V2")
    utils::globalVariables ("group_by_at")
    utils::globalVariables ("tally")
    utils::globalVariables ("separate")
    utils::globalVariables ("left_join")
    utils::globalVariables ("graph_from_data_frame")
    utils::globalVariables ("V")
    utils::globalVariables ("V<-")
    utils::globalVariables ("degree")
    utils::globalVariables ("betweenness")
    utils::globalVariables ("closeness")
    utils::globalVariables ("eigen_centrality")
    utils::globalVariables ("cluster_leading_eigen")
    utils::globalVariables ("fromJSON")
    utils::globalVariables ("cluster_leading_eigen")
    utils::globalVariables ("stringdist")
    invisible ()
}
